### PR TITLE
Projects page

### PR DESCRIPTION
**Pull request by lemurian33**

### CODE REVIEW

**Review by AndyRama — APPROVED** [review]
good jobs ok for projects_pages validation ok

**Comment by AndyRama** [comment]
ok for me

**Review by AndyRama — APPROVED** [review]
ok

**Review by AndyRama — APPROVED** [review]
ok

**Review by lemurian33 — COMMENTED** [review]
OK

**Review by AndyRama — APPROVED** [review]
good work

**Pull request merged**
